"""Cria tabelas iniciais de conversas, mensagens e análises

Revision ID: 30788b2fc561
Revises: a1e7a18af953
Create Date: 2025-08-04 13:13:46.186559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30788b2fc561'
down_revision: Union[str, Sequence[str], None] = 'a1e7a18af953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judicial_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('recommended_action', sa.JSON(), nullable=False),
    sa.Column('legal_rationale', sa.Text(), nullable=False),
    sa.Column('conservative_thesis', sa.JSON(), nullable=True),
    sa.Column('strategic_thesis', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('judicial_analyses')
    # ### end Alembic commands ###
