"""Cria tabelas iniciais de conversas, mensagens e análises

Revision ID: a1e7a18af953
Revises: 41513ea888f2
Create Date: 2025-07-31 19:35:42.318136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e7a18af953'
down_revision: Union[str, Sequence[str], None] = '41513ea888f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('kpis', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('advisor_recommendation', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('context', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('formal_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'formal_summary')
    op.drop_column('analyses', 'context')
    op.drop_column('analyses', 'advisor_recommendation')
    op.drop_column('analyses', 'kpis')
    # ### end Alembic commands ###
